1D-bit: 1D-bit.cpp
	g++ 1D-bit.cpp -o 1D-bit

2D-bit: 2D-bit.cpp
	g++ 2D-bit.cpp -o 2D-bit

order-statistic: order-statistic.cpp
	g++ order-statistic.cpp -o order-statistic

max-subsequence: max-subsequence.cpp
	g++ max-subsequence.cpp -o max-subsequence

clean:
	rm -rf 1D-bit 2D-bit order-statistic max-subsequence

