template1: template1.cpp
	g++ template1.cpp -o template1

specialization: specialization.cpp
	g++ specialization.cpp -o specialization

partial: partial.cpp
	g++ -std=c++14 partial.cpp -o partial

clean:
	rm -rf template1 specialization partial
