// Code generated by MockGen. DO NOT EDIT.
// Source: prototypes/mock/doer (interfaces: Doer)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDoer is a mock of Doer interface
type MockDoer struct {
	ctrl     *gomock.Controller
	recorder *MockDoerMockRecorder
}

// MockDoerMockRecorder is the mock recorder for MockDoer
type MockDoerMockRecorder struct {
	mock *MockDoer
}

// NewMockDoer creates a new mock instance
func NewMockDoer(ctrl *gomock.Controller) *MockDoer {
	mock := &MockDoer{ctrl: ctrl}
	mock.recorder = &MockDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDoer) EXPECT() *MockDoerMockRecorder {
	return m.recorder
}

// ReceiveFrom mocks base method
func (m *MockDoer) ReceiveFrom(arg0 string, arg1 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveFrom", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// ReceiveFrom indicates an expected call of ReceiveFrom
func (mr *MockDoerMockRecorder) ReceiveFrom(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveFrom", reflect.TypeOf((*MockDoer)(nil).ReceiveFrom), arg0, arg1)
}

// SendTo mocks base method
func (m *MockDoer) SendTo(arg0 string, arg1 int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTo", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTo indicates an expected call of SendTo
func (mr *MockDoerMockRecorder) SendTo(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTo", reflect.TypeOf((*MockDoer)(nil).SendTo), arg0, arg1, arg2)
}
